### ISSUE TITLE
unable to install in R

### ISSUE THREAD

**Issue by agovindj** [ColumbusCollaboratory/cognizer#3]
> devtools::install_github("ColumbusCollaboratory/cognizeR")
> Error in curl::handle_setopt(handle, .list = req$options) : 
>   A libcurl function was given a bad argument

**Comment by slavaua87** [comment]
Install call is misspelled. devtools::install_github("ColumbusCollaboratory/cognizer"). Lower case R.

**Comment by agovindj** [comment]
Still doesn't work with case change.

> devtools::install_github("ColumbusCollaboratory/cognizer")
Error in curl::handle_setopt(handle, .list = req$options) : 
  A libcurl function was given a bad argument

**Comment by slavaua87** [comment]
You also need a development version of curl. Do install.packages("https://github.com/jeroenooms/curl/archive/master.tar.gz", repos = NULL), and then devtools::install_github("ColumbusCollaboratory/cognizer"). I updated README to reflect this.

**Comment by slavaua87** [comment]
Are you on some flavor Windows?

**Comment by agovindj** [comment]
No a brand-new Mac.  

I did execute:
 install.packages("https://github.com/jeroenooms/curl/archive/master.tar.gz", repos = NULL) successfully but I still get the same error:
devtools::install_github("ColumbusCollaboratory/cognizer")
Error in curl::handle_setopt(handle, .list = req$options) : 
A libcurl function was given a bad argument

**Comment by slavaua87** [comment]
What's your libcurl version? You can check with curl --version in terminal. We have it working  with versions 7.43.0 and 7.47.0, on macs. The error does not seem to be with cognizer, but with curl. Can you download any other packages from github using install_github?

**Comment by agovindj** [comment]
curl --version is 7.43.0 -- and you're right i have the same error with another package. so it's nothing to do with cognizer. i will review my environment and see if I can discover the issue. Thanks for the follow up.
